[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm install -g elm && npm install --no-optional && npm run build"

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
